describe('admin using the app', () => {

    it('creates new unit and deletes it', () => {
        cy.visit('/')
        cy.getByText(/log in/i).click()
        cy.getByText(/units/i).click()
        cy.getByText(/add new unit/i).click()
        cy.getByLabelText(/name/i).type('Test unit')
        cy.getByLabelText(/description/i).type('Test desc')
        cy.getByLabelText(/url/i).type('https://iu.edu')
        cy.getByText('Save').click()
        cy.getByText('Test unit').click()
        cy.getByTitle(/Delete:/).click()
        cy.queryByText('Test unit').should('not.exist')
    })
    it('adds unit member & tool auth -> removes tool auth then member', () => {
        cy.visit('/')
        cy.getByText(/log in/i).click()
        cy.visit('/units/2')
        cy.getByTitle(/edit/i).click()
        cy.getByText(/add member/i).click()
        cy.getByLabelText(/search/i).type('sebastian')
        cy.getByText(/sebastian/i).click()
        cy.getByText(/submit addition/i).click()
        cy.queryByText(/sebastian/i).should("be.visible")
        cy.getByTitle(/edit tools/i).click()
        cy.getByLabelText(/survey/i).check({ force: true })
        cy.getByText(/update/i).click()
        cy.getByTitle(/edit tools/i).click()
        cy.getByLabelText(/survey/i).should("be.checked")
        cy.getByLabelText(/survey/i).uncheck({ force: true })
        cy.getByText(/update/i).click()
        cy.getByTitle(/edit tools/i).click()
        cy.getByLabelText(/survey/i).should("not.be.checked")
        cy.getByText(/update/i).click()
        cy.getByTitle(/remove member/i).click()
        cy.queryByText(/sebastian/i).should("not.be.visible")
    })
})